### ISSUE TITLE
Are offsets supported ?

### ISSUE THREAD

**Issue by jr-leary7** [kshedden/GEE.jl#1]
Hello ! I've recently been using your package to fit GEE models in Julia. It's worked quite well for the most part, and I appreciate all the effort you've put into it. One question - is it possible to include an offset for exposure time in the formula like is done in R ? I have a model I'd like to build using the following code, but it errors out because the offset term is undefined:

```
# libraries 
using DataFrames
using Distributions
using StatsModels
using EstimatingEquationsRegression
# model
geemod_julia = fit(GeneralizedEstimatingEquationsModel, 
                                @formula(seizures ~ offset(log(exposure)) + age + trt), 
                                seizure, 
                                seizure[:, :id], 
                                Poisson(), 
                                ExchangeableCor(), 
                                LogLink())'
```

This is using the widely-known seizures dataset that's included in the `geepack` R package. Any advice would be greatly appreciated !

**Comment by kshedden** [comment]
There is a keyword argument called 'offset' that you can use, but there is no way to put the offset directly into the formula like in R.

**Comment by jr-leary7** [comment]
Thank you so much ! For anyone else wondering, the following code worked perfectly: 

```
geemod_julia = fit(GeneralizedEstimatingEquationsModel, 
                                @formula(seizures ~ age + trt), 
                                seizure, 
                                seizure[:, :id], 
                                Poisson(), 
                                ExchangeableCor(), 
                                LogLink(), 
                                offset=seizure[:, :log_exposure])
```
